// <auto-generated />
namespace _01_Code_First_Student_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLicenses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLicenses));
        
        string IMigrationMetadata.Id
        {
            get { return "201703111834124_AddLicenses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
